language: node_js
node_js:
  - '10'
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
script:
  - npm run test
before_deploy:
  - git checkout -b master
  - npm version --no-git-tag-version ${TRAVIS_TAG}
  - git status
  - git add .
  - git commit -m "Version updated to ${TRAVIS_TAG}"
  - git push https://${GITHUB_TOKEN}@github.com/oscasais/passHashGenerator.git master
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
    tags: true