language: node_js
node_js:
  - '10'
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
script:
  - npm run test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  tag: next