language: node_js
node_js:
  - '10'
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
script:
  - npm run test
before_deploy:
  - npm version $TRAVIS_TAG
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
    tags: true
after_deploy:
  - git checkout -b master
  - git add package.json package-lock.json
  - git commit --message "Travis build: $TRAVIS_TAG"
  - git push -q https://${GITHUB_TOKEN}@github.com/oscasais/.git master